#' Fit a mark-recapture model
#'
#' Fits the multistate mark recapture model using cmdstanr. Most of the
#' arguments to this function are inherited from the `sample()` method in
#' cmdstanr, providing fine-tuned control over the posterior sampling.
#'
#' To use within-chain parallelization, provide the following arguments:
#'
#' 1. `cpp_options = list(stan_threads = TRUE)` to compile with threading
#'
#' 2. `threads_per_chain` set to some integer value > 1.
#'
#' `mrmr2` extends `mrmr`'s original model (`model = "base"`) with two
#' optional detection random-effect structures, in which detection
#' probability is otherwise a purely deterministic function of any
#' user-supplied `capture_formula` covariates:
#'
#' - `"detect_re"` adds a between-primary-period random effect
#' (`sigma_detect_period`) and a within-primary-period, per-survey random
#' effect (`sigma_detect_occasion`) to detection probability. This mainly
#' corrects overconfident (too-narrow) uncertainty intervals on `N` and `B`
#' when true detectability drifts across periods or occasions; it has little
#' effect on point estimates. With few secondary periods per primary period,
#' `sigma_detect_period` can absorb some real occasion-level noise as
#' apparent period-level drift (a small-sample identifiability artifact) --
#' compare its posterior to an expected `sigma_detect_occasion / sqrt(J)`
#' noise floor before concluding there is genuine period-to-period drift.
#' - `"indiv_re"` adds an individual-level random effect
#' (`sigma_detect_indiv`) so that some individuals can be persistently
#' harder to detect than others. Unlike `"detect_re"`, ignoring this kind of
#' heterogeneity (when present) causes a genuine negative bias in point
#' estimates of `N` (chronically-undetected individuals go undercounted),
#' not just overconfident intervals.
#'
#' Both extensions cost more than the `"base"` model: longer runtimes, and
#' (for `"indiv_re"`) substantially larger saved fit sizes, since its random
#' effect has one entry per augmented individual (`M`, the superpopulation
#' size) rather than one per primary period or survey. `"detect_re"` fits
#' can also require a higher `adapt_delta` than the default to avoid
#' divergent transitions when one of its two variance components is at or
#' near zero; if `model = "detect_re"` and `adapt_delta` is left unspecified,
#' it defaults to 0.95 rather than cmdstanr's usual 0.8.
#'
#' @param data A list of data generated by the function
#' \code{mrmr2::clean_data()}.
#' @param model Which Stan model to fit. One of `"base"` (the default; no
#' detection random effects), `"detect_re"` (adds between-period and
#' within-period/occasion detection random effects), or `"indiv_re"` (adds
#' an individual-level detection random effect). See Details.
#' @inheritParams cmdstanr::cmdstan_model
#' @inheritParams cmdstanr::sample
#' @return A list containing the model object, extracted posterior draws,
#' input data, and the name of the `model` that was fit.
#' @examples
#' \dontrun{
#' captures <- system.file("extdata", "capture-example.csv", package = "mrmr2") |>
#'   readr::read_csv()
#' translocations <- system.file("extdata", "translocation-example.csv",
#'                               package = "mrmr2") |>
#'   readr::read_csv()
#' surveys <- system.file("extdata", "survey-example.csv", package = "mrmr2") |>
#'   readr::read_csv()
#' out <- clean_data(captures, surveys, translocations)
#'
#' # fit a model with 4 chains, 2 threads per chain (to use 8 physical cores)
#' fit_model(
#'   data = out,
#'   chains = 4,
#'   parallel_chains = 4,
#'   cpp_options = list(stan_threads = TRUE),
#'   threads_per_chain = 2
#' )
#' }
#' @export

fit_model <- function(
  data,
  model = c("base", "detect_re", "indiv_re"),
  seed = NULL,
  refresh = NULL,
  init = NULL,
  save_latent_dynamics = FALSE,
  output_dir = NULL,
  output_basename = NULL,
  sig_figs = NULL,
  chains = 4,
  parallel_chains = getOption("mc.cores", 1),
  chain_ids = seq_len(chains),
  threads_per_chain = NULL,
  opencl_ids = NULL,
  iter_warmup = 1000,
  iter_sampling = 1000,
  save_warmup = FALSE,
  thin = NULL,
  max_treedepth = NULL,
  adapt_engaged = TRUE,
  adapt_delta = NULL,
  step_size = NULL,
  metric = NULL,
  metric_file = NULL,
  inv_metric = NULL,
  init_buffer = NULL,
  term_buffer = NULL,
  window = NULL,
  fixed_param = FALSE,
  show_messages = TRUE,
  show_exceptions = TRUE,
  diagnostics = c("divergences", "treedepth", "ebfmi"),
  save_metric = getOption("cmdstanr_save_metric", FALSE),
  save_cmdstan_config = getOption("cmdstanr_save_config", FALSE),
  compile = TRUE,
  ...
  ) {

  model <- match.arg(model)

  stan_filename <- switch(
    model,
    base = "twostate.stan",
    detect_re = "twostate_detect_re.stan",
    indiv_re = "twostate_indiv_re.stan"
  )

  stan_file <- system.file(
    "extdata", stan_filename, package = "mrmr2", mustWork = TRUE
  )

  # twostate_detect_re.stan's two variance components (sigma_detect_period,
  # sigma_detect_occasion) are only weakly separable, which can produce
  # divergent transitions near their zero boundary at cmdstanr's default
  # adapt_delta.
  if (model == "detect_re" && is.null(adapt_delta)) {
    adapt_delta <- 0.95
  }

  stan_model <- cmdstanr::cmdstan_model(stan_file, compile = compile, ...)

  m_fit <- stan_model$sample(
    data = data$stan_d,
    seed = seed,
    refresh = refresh,
    init = init,
    save_latent_dynamics = save_latent_dynamics,
    output_dir = output_dir,
    output_basename = output_basename,
    sig_figs = sig_figs,
    chains = chains,
    parallel_chains = parallel_chains,
    chain_ids = chain_ids,
    threads_per_chain = threads_per_chain,
    opencl_ids = opencl_ids,
    iter_warmup = iter_warmup,
    iter_sampling = iter_sampling,
    save_warmup = save_warmup,
    thin = thin,
    max_treedepth = max_treedepth,
    adapt_engaged = adapt_engaged,
    adapt_delta = adapt_delta,
    step_size = step_size,
    metric = metric,
    metric_file = metric_file,
    inv_metric = inv_metric,
    init_buffer = init_buffer,
    term_buffer = term_buffer,
    window = window,
    fixed_param = fixed_param,
    show_messages = show_messages,
    show_exceptions = show_exceptions,
    diagnostics = diagnostics,
    save_metric = save_metric,
    save_cmdstan_config = save_cmdstan_config
  )

  # Load all the data and return the whole unserialized fit object:
  # https://github.com/stan-dev/cmdstanr/blob/d27994f804c493ff3047a2a98d693fa90b83af98/R/fit.R#L16-L18 # nolint
  m_fit$draws() # Do not specify variables or inc_warmup.
  try(m_fit$sampler_diagnostics(), silent = TRUE)
  try(m_fit$init(), silent = TRUE)
  try(m_fit$profiles(), silent = TRUE)

  list(m_fit = m_fit, data = data, model = model)
}
