#' Plot a mark-recapture model's output
#'
#' @param model A model objectgenerated by \code{mrmr2:fit_model()}.
#' @param what What to plot. Must be a character string of either
#' "abundance", "recruitment", "f_survival", or "p_survival".
#' @return A ggplot object.
#' @details For \code{what = "f_survival"} and \code{what = "p_survival"},
#' only the posterior draws of the latent state (\code{s}) for real
#' (non data-augmented) individuals are pulled from the fit, rather than for
#' every individual (real and data-augmented pseudo-individual) tracked by
#' the model. This keeps memory use for these plots low even for sites with
#' a large augmented superpopulation.
#'
#' \code{what = "f_survival"} plots the fraction of each translocated or
#' reintroduced cohort estimated to still be alive, as a function of time
#' since introduction -- a cumulative, cohort-relative statistic that
#' requires addition data and only describes translocated/reintroduced
#' individuals.
#'
#' \code{what = "p_survival"} instead plots the estimated period-to-period
#' survival probability (the probability that an individual alive in one
#' primary period is still alive in the next) for all real individuals in
#' the population. Unlike \code{what = "f_survival"}, this statistic is not
#' cumulative from a fixed start date, so it stays directly comparable
#' across groups regardless of how long each has been tracked. If the model
#' was fit with a \code{survival_formula} (see the \code{survival_formula}
#' and \code{survival_fill_value} arguments to \code{\link{clean_data}}),
#' one line is plotted per covariate category (categories from multiple
#' covariates are combined); this assumes survival covariates are
#' categorical, which \code{survival_fill_value}'s requirements already
#' push users toward. If no survival covariates were fit, a single,
#' ungrouped line is plotted for the whole population -- any apparent
#' difference between subgroups (e.g. added vs. resident individuals) is
#' not something the model actually estimated unless a covariate
#' distinguishing them was included.
#' @examples
#' \dontrun{
#' captures <- system.file("extdata", "capture-example.csv", package = "mrmr2")
#' additions <- system.file("extdata", "translocation-example.csv",
#'                          package = "mrmr2")
#' surveys <- system.file("extdata", "survey-example.csv", package = "mrmr2")
#' out <- clean_data(captures = captures, surveys = surveys,
#'                   additions = additions)
#' model <- fit_model(out, chains = 1, iter = 10)
#' plot_model(model, what = "abundance")
#' }
#' @export
#' @importFrom dplyr group_by summarize left_join ungroup filter distinct
#'   rename arrange lead
#' @importFrom ggplot2 ggplot geom_line geom_ribbon xlab ylab facet_wrap theme
#'   scale_color_brewer aes element_text scale_fill_brewer geom_point
#'   geom_vline geom_text geom_linerange ylim
#' @importFrom reshape2 melt
#' @importFrom rlang .data
#' @importFrom tibble as_tibble
#' @importFrom stats median quantile

plot_model <- function(model, what) {
  valid_plots <- c("abundance", "recruitment", "f_survival", "p_survival")
  stopifnot(what %in% valid_plots)
  any_additions <- 'data.frame' %in% class(model$data$additions)

  if (what == "f_survival") {
    if (!any_additions) {
      stop(paste("No addition data (translocations or reintroductions) are",
                 "present, so a cohort survival plot cannot be generated.",
                 "Using what='f_survival' requires addition data."))
    }

    primary_period_dates <- model$data$surveys |>
      group_by(.data$primary_period) |>
      summarize(date = min(.data$survey_date),
                year = min(.data$year))

    addition_dates <- distinct(
      model$data$additions,
      .data$pit_tag_id,
      .data$release_date
    )

    # Only pull the latent-state draws ("s") for translocated individuals,
    # rather than the full M x T array for every real and pseudo-individual
    # in the augmented superpopulation. Filtering via `draws(variables = )`
    # before pivoting avoids materializing the (much larger) unfiltered
    # array, which can otherwise dominate this function's memory use.
    pit_tag_ids <- dimnames(model$data$stan_d$Y)[[1]]
    n_periods <- ncol(model$data$stan_d$Y)
    addition_idx <- which(
      pit_tag_ids %in% as.character(model$data$additions$pit_tag_id)
    )
    s_varnames <- paste0(
      "s[", rep(addition_idx, each = n_periods), ",",
      rep(seq_len(n_periods), times = length(addition_idx)), "]"
    )

    p <- model$m_fit$draws(variables = s_varnames, format = "draws_df") |>
      tidyr::pivot_longer(tidyselect::starts_with('s')) |>
      suppressWarnings() |>
      mutate(get_numeric_indices(.data$name)) |>
      rename(
        primary_period = .data$index_2
      ) |>
      mutate(pit_tag_id = pit_tag_ids[.data$index_1]) |>
      left_join(addition_dates, by = "pit_tag_id") |>
      group_by(.data$release_date, .data$primary_period, .data$.draw) |>
      summarize(fraction_alive = mean(.data$value == 2), .groups = "drop") |>
      filter(.data$primary_period > 1) |>
      left_join(primary_period_dates, by = "primary_period") |>
      filter(.data$date >= .data$release_date) |>
      group_by(.data$release_date, .data$date, .data$year) |>
      summarize(lo = quantile(.data$fraction_alive, .025),
                med = median(.data$fraction_alive),
                hi = quantile(.data$fraction_alive, .975),
                .groups = "drop") |>
      ggplot(aes(.data$date, .data$med,
                 color = as.factor(.data$release_date),
                 fill = as.factor(.data$release_date))) +
      geom_ribbon(aes(ymin = .data$lo, ymax = .data$hi),
                  alpha = .5, color = NA) +
      geom_point() +
      geom_line() +
      ylab('Fraction surviving') +
      xlab('Date') +
      scale_color_brewer('Introduction date', type = 'qual', palette = 'Dark2') +
      scale_fill_brewer('Introduction date', type = 'qual', palette = 'Dark2') +
      facet_wrap(~.data$year, nrow = 1, scales = 'free_x') +
      theme(axis.text.x = element_text(angle = 90),
            legend.position = "top")
  } else if (what == "p_survival") {
    primary_period_dates <- model$data$surveys |>
      group_by(.data$primary_period) |>
      summarize(date = min(.data$survey_date),
                year = min(.data$year))

    # Group by the model's own survival covariate(s), if any were fit,
    # rather than assuming a particular split (e.g. added vs. resident) --
    # this keeps the plot honest about what the model can actually
    # distinguish. survival_covariate_df holds covariate values in their
    # original (typically categorical) form, one row per real individual;
    # it has only a pit_tag_id column when no survival_formula was used.
    covariate_cols <- setdiff(names(model$data$survival_covariate_df),
                              "pit_tag_id")
    has_survival_covariates <- length(covariate_cols) > 0

    # As in what = 'f_survival', only pull the latent-state draws ("s") for
    # real individuals, rather than the full M x T array for every real and
    # pseudo-individual in the augmented superpopulation.
    pit_tag_ids <- dimnames(model$data$stan_d$Y)[[1]]
    n_periods <- ncol(model$data$stan_d$Y)
    real_idx <- which(!grepl("^aug", pit_tag_ids))
    s_varnames <- paste0(
      "s[", rep(real_idx, each = n_periods), ",",
      rep(seq_len(n_periods), times = length(real_idx)), "]"
    )

    s_pairs <- model$m_fit$draws(variables = s_varnames, format = "draws_df") |>
      tidyr::pivot_longer(tidyselect::starts_with('s')) |>
      suppressWarnings() |>
      mutate(get_numeric_indices(.data$name)) |>
      rename(primary_period = .data$index_2) |>
      mutate(pit_tag_id = pit_tag_ids[.data$index_1])

    if (has_survival_covariates) {
      legend_title <- paste(covariate_cols, collapse = " / ")
      group_lookup <- model$data$survival_covariate_df |>
        tidyr::unite("group", tidyselect::all_of(covariate_cols), sep = ", ")
      s_pairs <- left_join(s_pairs, group_lookup, by = "pit_tag_id")
    } else {
      s_pairs <- mutate(s_pairs, group = "All individuals")
    }

    # Period-to-period survival: condition on being alive (state == 2) at
    # primary period t, and ask whether the individual is still alive at
    # t + 1. Unlike 'f_survival', this isn't cumulative from a fixed start
    # date, so different covariate categories are directly comparable at
    # any shared date, regardless of how long each has been tracked.
    p <- s_pairs |>
      select("pit_tag_id", "group", "primary_period", ".draw", "value") |>
      arrange(.data$pit_tag_id, .data$.draw, .data$primary_period) |>
      group_by(.data$pit_tag_id, .data$.draw) |>
      mutate(next_value = lead(.data$value),
             next_period = lead(.data$primary_period)) |>
      ungroup() |>
      filter(.data$value == 2, !is.na(.data$next_value)) |>
      group_by(.data$group, .data$next_period, .data$.draw) |>
      summarize(survived = mean(.data$next_value == 2), .groups = "drop") |>
      rename(primary_period = .data$next_period) |>
      left_join(primary_period_dates, by = "primary_period") |>
      group_by(.data$group, .data$date, .data$year) |>
      summarize(lo = quantile(.data$survived, .025),
                med = median(.data$survived),
                hi = quantile(.data$survived, .975),
                .groups = "drop") |>
      ggplot(aes(.data$date, .data$med,
                 color = .data$group, fill = .data$group)) +
      geom_ribbon(aes(ymin = .data$lo, ymax = .data$hi),
                  alpha = .3, color = NA) +
      geom_point() +
      geom_line() +
      ylim(0, 1) +
      ylab('Probability of survival\nto next primary period') +
      xlab('Date') +
      facet_wrap(~.data$year, nrow = 1, scales = 'free_x') +
      theme(axis.text.x = element_text(angle = 90),
            legend.position = "top")

    if (has_survival_covariates) {
      p <- p +
        scale_color_brewer(legend_title, type = 'qual', palette = 'Dark2') +
        scale_fill_brewer(legend_title, type = 'qual', palette = 'Dark2')
    } else {
      p <- p +
        scale_color_brewer(type = 'qual', palette = 'Dark2', guide = "none") +
        scale_fill_brewer(type = 'qual', palette = 'Dark2', guide = "none")
    }
  } else {
    survey_prim_periods <- model$data$surveys |>
      group_by(.data$primary_period) |>
      filter(.data$secondary_period == min(.data$secondary_period))

    survey_prim_periods <- ungroup(survey_prim_periods)

    if (what == "abundance") {
      p <- model$m_fit$draws("N", format = "draws_df") |>
        tidyr::pivot_longer(tidyselect::starts_with("N")) |>
        suppressWarnings() |>
        mutate(
          get_numeric_indices(.data$name),
          primary_period = .data$index_1 + 1
        ) |>
        group_by(.data$primary_period) |>
        summarize(lo = quantile(.data$value, .025),
                  med = median(.data$value),
                  hi = quantile(.data$value, .975),
                  .groups = "drop") |>
        left_join(survey_prim_periods, by = "primary_period") |>
        ggplot(aes(.data$survey_date, .data$med)) +
        geom_line() +
        geom_point() +
        geom_ribbon(aes(ymin = .data$lo, ymax = .data$hi), alpha = .4) +
        geom_linerange(aes(ymin = .data$lo, ymax = .data$hi), alpha = .4) +
        xlab('Date') +
        ylab('Population size') +
        facet_wrap(~.data$year, nrow = 1, scales = 'free_x') +
        theme(axis.text.x = element_text(angle = 90))
    }

    if (what == "recruitment") {
      p <- model$m_fit$draws("B", format = "draws_df") |>
        tidyr::pivot_longer(tidyselect::starts_with("B")) |>
        suppressWarnings() |>
        mutate(
          get_numeric_indices(.data$name),
          primary_period = .data$index_1 + 1
        ) |>
        group_by(.data$primary_period) |>
        summarize(lo = quantile(.data$value, .025),
                  med = median(.data$value),
                  hi = quantile(.data$value, .975),
                  .groups = "drop") |>
        left_join(survey_prim_periods, by = "primary_period") |>
        ggplot(aes(.data$survey_date, .data$med)) +
        geom_line() +
        geom_point() +
        geom_ribbon(aes(ymin = .data$lo, ymax = .data$hi), alpha = .4) +
        geom_linerange(aes(ymin = .data$lo, ymax = .data$hi), alpha = .4) +
        xlab('Date') +
        ylab('Recruitment') +
        facet_wrap(~.data$year, nrow = 1, scales = 'free_x') +
        theme(axis.text.x = element_text(angle = 90))
    }

    if (any_additions) {
      addition_sums <- model$data$additions |>
        group_by(.data$release_date) |>
        summarize(n = length(unique(.data$pit_tag_id))) |>
        mutate(year = lubridate::year(.data$release_date))
      p <- p +
        geom_vline(aes(xintercept = .data$release_date),
                   linetype = "dashed",
                   data = addition_sums) +
        geom_text(aes(x = .data$release_date,
                      y = -Inf,
                      label = paste0(" +", .data$n)),
                  data = addition_sums,
                  vjust = -1,
                  hjust = 0)
    }

  }

  return(p)
}

#' Get numeric indices from a string representation
#' @param string input string
#'
#' @export
get_numeric_indices <- function(string) {
  idx_mat <- stringr::str_extract_all(string, "[0-9]+", simplify = TRUE)
  colnames(idx_mat) <- paste0("index_", seq_len(ncol(idx_mat)))
  tibble::as_tibble(idx_mat) |>
    dplyr::mutate_all(readr::parse_integer)
}
